#!/bin/bash
#PBS -P UNITI
#PBS -N AnnotSV
#PBS -l select=1:ncpus=24:mem=100GB
#PBS -l walltime=288:00:00
#PBS -q defaultQ
#PBS -W umask=022

# Load any necessary modules, e.g., for bedtools
module load annotsv 
module load bedtools 

# Define the input directory, output directory, and input file
INPUT_DIR="/scratch/RDS-FMH-UNITI-RW/FASTQ_BAM_READS/gzfiles/SVDB/output/I1subgroup"
OUTPUT_DIR="/scratch/RDS-FMH-UNITI-RW/FASTQ_BAM_READS/gzfiles/SVDB/output/I1subgroup/AnnotSV"
ANNOTSV_BIN="$ANNOTSV/bin/AnnotSV"
BEDTOOLS_PATH="/usr/local/bedtools/2.29.2/bin/bedtools"

# Specify the single VCF.gz file to process
INPUT_FILE="${INPUT_DIR}/final.vcf.gz"

# Get the base name of the file
BASENAME=$(basename "$INPUT_FILE")

# Run AnnotSV on the single file
"$ANNOTSV_BIN" -SVinputFile "$INPUT_FILE" \
               -outputDir "$OUTPUT_DIR" \
               -outputFile "$BASENAME" \
               -typeOfAnnotation split \
               -bedtools "$BEDTOOLS_PATH" \
               -addCytoband \
               -addGeneSymbol \
               -addTranscriptID \
               -addOverlappedTranscriptLength \
               -addOverlappedCDSLength \
               -addLocationInGene \
               -acmg

# Print completion message
echo "AnnotSV annotation complete for file $INPUT_FILE. Output written to $OUTPUT_DIR/$BASENAME"

